const PUBLIC_TOKEN_CACHE_EXPIRATION = 7_100; // 2 horas de expiração
const PATIENT_TOKEN_EXPIRATION = 3_300; // 1 hora
const PATIENT_PRE_SCHEDULE_CODE_EXPIRATION = 172_800; // 2 dias de cache
const PATIENT_APPOINTMENTS_CACHE_EXPIRATION = 60; // 60 segundos de cache
const MATRIX_TOKEN_EXPIRATION = 60; // 60 segundos de cache
const MATRIX_AUTH_TOKEN_EXPIRATION = 20 * 60; // 20 minutos de cache

const DEFAULTS_MATRIX_SOAP_URL = 'https://meuexame.tecnolab.com.br/resultadosnet/wsrvPortalNet.svc?singleWsdl';
const DEFAULTS_MATRIX_SOAP_PASSWORD = 'Boot@2024';
const DEFAULTS_MATRIX_SOAP_TOKEN = undefined;
const DEFAULTS_MATRIX_SOAP_USER = 'BOOTDESIGNER';

export {
  PUBLIC_TOKEN_CACHE_EXPIRATION,
  PATIENT_TOKEN_EXPIRATION,
  PATIENT_PRE_SCHEDULE_CODE_EXPIRATION,
  PATIENT_APPOINTMENTS_CACHE_EXPIRATION,
  DEFAULTS_MATRIX_SOAP_URL,
  DEFAULTS_MATRIX_SOAP_PASSWORD,
  DEFAULTS_MATRIX_SOAP_TOKEN,
  DEFAULTS_MATRIX_SOAP_USER,
  MATRIX_TOKEN_EXPIRATION,
  MATRIX_AUTH_TOKEN_EXPIRATION,
};
