import { EntityType } from '../interfaces/entity.interface';

const ENTITIES_CACHE_EXPIRATION = 12_000;
const DOCTORS_FROM_SCHEDULE_LIST_CACHE_EXPIRATION = 600;
const SCHEDULE_VALUE_CACHE_EXPIRATION = 1_800;
const PATIENT_CACHE_EXPIRATION = 10_800;
const PATIENT_SCHEDULES_CACHE_EXPIRATION = 1_200;
const PROCESSED_ENTITIES_CACHE_EXPIRATION = 120;
const SPECIALITIES_FROM_DOCTORS_CACHE_EXPIRATION = 1_200;
const SCHEDULED_SENDING_CACHE_EXPIRATION = 36_000;
const PATIENT_SCHEDULE_CONFIRMATION_CACHE_EXPIRATION = 43_200;
const API_QUEUE_CACHE_EXPIRATION = 300;
const LIST_SCHEDULES_TO_CONFIRM = 300;

const getExpirationByEntity = (entity: EntityType): number => {
  switch (entity) {
    case EntityType.insurancePlan:
    case EntityType.insuranceSubPlan:
    case EntityType.planCategory:
      return ENTITIES_CACHE_EXPIRATION * 2;

    default:
      return ENTITIES_CACHE_EXPIRATION;
  }
};

export {
  ENTITIES_CACHE_EXPIRATION,
  DOCTORS_FROM_SCHEDULE_LIST_CACHE_EXPIRATION,
  SCHEDULE_VALUE_CACHE_EXPIRATION,
  PATIENT_CACHE_EXPIRATION,
  PATIENT_SCHEDULES_CACHE_EXPIRATION,
  PROCESSED_ENTITIES_CACHE_EXPIRATION,
  SPECIALITIES_FROM_DOCTORS_CACHE_EXPIRATION,
  SCHEDULED_SENDING_CACHE_EXPIRATION,
  PATIENT_SCHEDULE_CONFIRMATION_CACHE_EXPIRATION,
  API_QUEUE_CACHE_EXPIRATION,
  LIST_SCHEDULES_TO_CONFIRM,
  getExpirationByEntity,
};
