app:
  http:
    replicaCount: 9
    args:
    - http
    ingress:
      host: "api.botdesigner.io"
      gateway: "gateway"
    resources:
      requests:
        cpu: 0.6
        memory: 600Mi
      limits:
        cpu: 0.9
        memory: "9000Mi"
  batch:
    replicaCount: 1
    enabled: true
  internal:
    replicaCount: 6
    enabled: true
    resources:
      requests:
        cpu: 0.4
        memory: 400Mi
      limits:
        cpu: 0.8
        memory: 900Mi
  envs:
    NODE_ENV: "production"
    APPLICATION_VERSION: "0.0.1"
    SYNCHRONIZE: "false"
    LOGGING: "true"
    JWT_EXPIRATION_TOKEN: "10000 days"
    MAILGUN_API_KEY: "123123"
    MAILGUN_DOMAIN: "123123123"
    MAINGUN_FROM: "no-reply@kissbot.com"
    MAILGUN_WORKSPACE: "asdasd"
    MAILGUN_USERNAME: "api"
    EXPIRATION_TIMEOUT_TOKEN_FORGET_PASSWORD_VALUE: "86400"
    REDIS_HOST: "redis-master.devops.svc.cluster.local"
    REDIS_HOST_ELASTICACHE: "redis-eks.md7wqi.ng.0001.sae1.cache.amazonaws.com"
    REDIS_PORT: "6379"
    ENGINE_URI: "http://botdesigner-engine.production.svc.cluster.local"
    EVENT_EXCHANGE_NAME: "events-production"
    GRAYLOG_HOST: "graylog-udp.devops.svc.cluster.local"
    GRAYLOG_PORT: "12222"
    GRAYLOG_ENABLED: "no"
    GRAYLOG_FACILITY: "api"
    ELK_SERVER_URI: "https://vpc-botdesignerio-47zkoyk6beizt6dh7clmwsggk4.sa-east-1.es.amazonaws.com"
    TZ: "America/Sao_Paulo"
    INTEGRATIONS_URI: "http://botdesigner-integrations.production.svc.cluster.local"
    INTEGRATIONS_URL: "https://integrations.botdesigner.io"
    AWS_WORKSPACE_BUCKET_REGION_NAME: "sa-east-1"
    AWS_WORKSPACE_BUCKET_NAME: "botdesigner-workspace-production"
    AWS_ATTACHMENTS_REGION_NAME : "sa-east-1"
    AWS_ATTACHMENTS_BUCKET_NAME : "botdesignerio-activity-media-production"
    CHANNEL_EXCHANGE_NAME: "channels-production"
    COGNITO_POOL_ID: "sa-east-1_6Oo6cvHy2"
    COGNITO_POOL_CLIENT_ID: "c027jsqpkbn0s01i550lln0af"
    API_URI: "https://api.botdesigner.io"
    RATING_APP_URI: "https://avaliacao.botdesigner.io"
    ASAAS_URI: "https://www.asaas.com"
    KAFKA_BROKERS: b-2.botdesignermsk.ez8kg4.c3.kafka.sa-east-1.amazonaws.com:9094,b-1.botdesignermsk.ez8kg4.c3.kafka.sa-east-1.amazonaws.com:9094
    KAFKA_USERNAME: mzygerix
    SENTRY_URI: ""
    NOTIFICATION_EMAIL: ""
    CHAT_SOCKET_URI: "https://chat-socket.botdesigner.io"
    AUTOMATIC_MESSAGE_URL: "http://botdesigner-automatic-message.production.svc.cluster.local"
service:
  type: ClusterIP
  port: 80
  targetPort: 9091
