import { generateId } from '../helpers/hex';

const getDefaultTags = (workspaceId: string) => [
    {
        workspaceId,
        name: '@bot.agendamento',
        inactive: false,
        color: '#5e8cf3',
        _id: generateId(24),
    },
    {
        workspaceId,
        name: '@bot.visualiza',
        inactive: false,
        color: '#60d394',
        _id: generateId(24),
    },
    {
        workspaceId,
        name: '@bot.confirma',
        inactive: false,
        color: '#61e8e1',
        _id: generateId(24),
    },
    {
        workspaceId,
        name: '@bot.cancela',
        inactive: false,
        color: '#cf5e69',
        _id: generateId(24),
    },
    {
        workspaceId,
        name: '@bot.reagendamento',
        inactive: false,
        color: '#aa5ecf',
        _id: generateId(24),
    },
    {
        workspaceId,
        name: '@bot.cadastro',
        inactive: false,
        color: '#b2cf5e',
        _id: generateId(24),
    },
    {
        workspaceId,
        name: '@bot.confirmacao.confirmado',
        inactive: false,
        color: '#7ed321',
        _id: generateId(24),
    },
    {
        workspaceId,
        name: '@bot.confirmacao.cancelado',
        inactive: false,
        color: '#c83244',
        _id: generateId(24),
    },
    {
        workspaceId,
        name: '@bot.confirmacao.cancelado_individual',
        inactive: false,
        color: '#d24c4c',
        _id: generateId(24),
    },
    {
        workspaceId,
        name: '@bot.confirmacao.reagendar',
        inactive: false,
        color: '#fdbc51',
        _id: generateId(24),
    },
    {
        workspaceId,
        name: '@bot.sugestao.convenio',
        inactive: false,
        color: '#76911b',
        _id: generateId(24),
    },
    {
        workspaceId,
        name: '@bot.paciente.dados.incorretos',
        inactive: false,
        color: '#1b916d',
        _id: generateId(24),
    },
    {
        workspaceId,
        name: '@bot.identificacao.paciente',
        inactive: false,
        color: '#1b5991',
        _id: generateId(24),
    },
    {
        workspaceId,
        name: '@bot.resgate.reagendar',
        inactive: false,
        color: '#355e8b',
        _id: generateId(24),
    },
    {
        workspaceId,
        name: '@sys_no_dates',
        inactive: false,
        color: '#ff6666',
        _id: generateId(24),
    },
    {
        workspaceId,
        name: '@bot.resgate_reagendou',
        inactive: false,
        color: '#007bff',
        _id: generateId(24),
    },
    {
        workspaceId,
        name: '@bot.resgate.nao_reagendou',
        inactive: false,
        color: '#417505',
        _id: generateId(24),
    },
    {
        workspaceId,
        name: '@bot.resgate.nao_sou_paciente',
        inactive: false,
        color: '#4a9361',
        _id: generateId(24),
    },
    {
        workspaceId,
        name: '@remi.finaliza',
        inactive: false,
        color: '#8e8f67',
        _id: generateId(24),
    },
    {
        workspaceId,
        name: '@remi.assume',
        inactive: false,
        color: '#678f78',
        _id: generateId(24),
    },
];

export default getDefaultTags;
