export enum ChannelIdConfig {
  webchat = 'webchat',
  webemulator = 'webemulator',
  emulator = 'emulator',
  wabox = 'wabox',
  whatsapp = 'whatsapp',
  sms = 'sms',
  gupshup = 'whatsapp-gupshup',
  d360 = 'whatsapp-d360',
  whatsweb = 'whatsweb',
  liveagent = 'live-agent',
  kissbot = 'kissbot',
  telegram = 'telegram',
  rating = 'rating',
  facebook = 'facebook',
  instagram = 'instagram',
  api = 'api',
  campaign = 'campaign',
  confirmation = 'confirmation',
  reminder = 'reminder',
  nps = 'nps',
  medical_report = 'medical_report',
  ads = 'ads',
}
