export enum FlowCategoryEnum {
  SIGN_UP = 'SIGN_UP',
  SIGN_IN = 'SIGN_IN',
  APPOINTMENT_BOOKING = 'APPOINTMENT_BOOKING',
  LEAD_GENERATION = 'LEAD_GENERATION',
  CONTACT_US = 'CONTACT_US',
  CUSTOMER_SUPPORT = 'CUSTOMER_SUPPORT',
  SURVEY = 'SURVEY',
  OTHER = 'OTHER',
}
