export const LOCAL_STORAGE_KEYS = {
  CURRENT_WORKSPACE: '@workspace',
  EMAILLOGIN: '@email',
  END_CONVERSATION_TEXT: '@endConversationText',
  LIVE_AGENT_FILTERS: '@liveAgentFilters',
  LIVE_AGENT_FILTERS_USERS: '@liveAgentFiltersUsers',
  RECENTLY_CHANNELS: '@recentlyChannels',
  LIVE_AGENT_SAVED_MESSAGES: '@liveAgentSavedMessages',
  CHANNEL_TO_START_CONVERSATIONS: '@channelToStartConversation',
  DASHBOARD_FILTER: '@dashboardFilter',
  DASHBOARD_FILTER_GRAPHICS: '@dashboardFilterGraphics',
  APPOINTMENT_FILTER: '@appointmentFilter',
  SOUND_CHAT: '@soundChat',
  PASSWORD_CHANGED: '@passwordChanged',
  TREE_COLLAPSED: '@treeCollapsed',
  LEAVE_CONVERSATION_ON_TRANSFER: '@leaveConversationOntransfer',
  RECENTLY_WORKSPACES: '@recentlyWorkspaces',
  DASHBOARD_REAL_TIME_TEAMS: '@dashboardRealTimeTeams',
  DASHBOARD_REAL_TIME_AGENTS: '@dashboardRealTimeAgents',
};
